safe: false
auto: false
server: false
server_port: 4000
baseurl: /
url: http://localhost:4000

source: .
destination: ./_site
exclude:
  - Gemfile
  - Gemfile.lock
  - karma.conf.js
  - Makefile
  - LICENSE
  - README.md
plugins: ./_plugins
